### ISSUE TITLE
Cannot find the paper Rethinking the Elementary function fusion for Single-Image Dehazing in the arxiv or other related  websites

### ISSUE THREAD

**Issue by msk7131** [YesianRohn/CL2S#1]
Cannot find the paper Rethinking the Elementary function fusion for Single-Image Dehazing in the arxiv or other related  websites

**Comment by msk7131** [comment]
would you please share

**Comment by YesianRohn** [comment]
This paper will release soon

**Comment by YesianRohn** [comment]
I have already submitted my paper to arXiv, but its status is currently on hold and it may take some more time for it to be processed.

**Comment by YesianRohn** [comment]
Now, the paper can be viewed at https://arxiv.org/abs/2405.15817
